language: c
# Avoid running in a container, as this doesn't work for the ocaml tests.
sudo: required
python:
  - "2.7"
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - pip install --user flake8
env:
  global:
    - OCAML_VERSION=4.04
    - DISTRO=debian-stable
    - PACKAGE=xapi-storage
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
script:
  - flake8 --show-source python --ignore E201,E202,E301,E302,E305,E501,F401,W292,E402,W503
  - bash -ex .travis-opam.sh
