language: c
# Avoid running in a container, as this doesn't work for the ocaml tests.
sudo: required
python:
  - "2.7"
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - pip install --user flake8
script:
  - flake8 --show-source python
  - bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=xapi-storage
